name: Deploy NutriTrack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Web01
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WEB01_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/NutriTrack
            git pull origin main
            npm install --production
            pm2 restart nutritrack

      - name: Deploy to Web02
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WEB02_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/NutriTrack
            git pull origin main
            npm install --production
            pm2 restart nutritrack
